services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
         daphne backend.asgi:application -b 0.0.0.0 -p 8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env